name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps: &setup
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci --ignore-scripts # suppress prepare script, pre-commit install

  format:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - *setup
      - run: npm run format:check # fairly quick, needs prettier installed

  lint:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - *setup
      - run: npm run lint # kind of slow compared to tests

  test:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - *setup
      - run: npm run build # build artifacts used for server smoke-test
      - run: npm run test

  build-server:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - run: npm run build:server # not really used in tests, but server should build
