name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  node-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
      - run: npm ci --ignore-scripts # suppress prepare script, pre-commit install
      - run: npm run format:check # fairly quick, needs prettier installed
      - run: npm run build # build artifacts used for server smoke-test
      - run: npm run test
      - run: npm run lint # kind of slow compared to tests
      - run: npm run build:server # not really used in tests, but server should build
