name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  setup-and-build-server:
    runs-on: ubuntu-latest
    steps:
      - &checkout
        uses: actions/checkout@v6
      - &setupnode
        uses: actions/setup-node@v6
        with:
          node-version: 22
          # cache: 'npm'
          # cache-dependency-path: package-lock.json
      - run: npm ci --ignore-scripts
        # suppress prepare script, pre-commit install
      - &npmci
        uses: actions/cache@v4
        id: cache-node_modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm run build:server # not really used in tests, but server should build

  format:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setupnode
      - *npmci
      - run: npm run format:check # fairly quick, needs prettier installed

  lint:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setupnode
      - *npmci
      - run: npm run lint # kind of slow compared to tests

  test:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setupnode
      - *npmci
      - run: npm run build # build artifacts used for server smoke-test
      - run: npm run test
